---
- hosts: all
  become: yes
  gather_facts: yes
  vars_files:
    - vars/default.yml
  tasks:

  ###########################################################
  #                                                         #
  #   Mount EFS locally into the Bastion host filesystem    #
  #                                                         #
  ###########################################################

  - name: Creating the directory *downloads* in {{ working_dir }}
    file:
      path: "{{ working_dir }}"
      state: directory
      mode: '0755'

  - name: Mounting AWS EFS into the directory {{ working_dir }}
    shell:
      cmd: mount -t nfs4 -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport {{ efs_file_system_id }}:/ {{ working_dir }}

  ##################################################
  #                                                #
  #   Wordpress installation                       #
  #                                                #
  ##################################################

  - name: Downloading latest version of Wordpress from the {{ wp_url_site }}
    get_url:
      url: "{{ wp_url_site }}"
      dest: "{{ wp_dest_path }}"
      mode: "{{ wp_dir_mode }}"

  - name: Extracting the wordpress.tar.gz file into {{ working_dir }}
    unarchive:
      src: "{{ wp_file_src }}"
      dest: "{{ wp_file_dest }}"
      remote_src: yes

  - name: Adding a user account *apache* to the bastion host OS
    group:
      name: apache
      state: present

  - name: Adding a user group *apache* to the bastion host OS
    user:
      name: apache
      group: apache
      shell: /sbin/nologin
      state: present

  - name: Creating the Wordpress configuration file wp-config.php
    template:
      src: "{{ wp_conf_template_file_src }}"
      dest: "{{ wp_conf_template_file_dest }}"

  - name: Changing directory's permission on {{ wp_working_dir }}
    file:
      path: "{{ wp_working_dir }}"
      owner: "{{ wp_dir_owner }}"
      group: "{{ wp_dir_group }}"
      mode: '0774'
      recurse: yes

  ##################################################
  #                                                #
  #   PHP 7.4 nstallation                          #
  #                                                #
  ##################################################

  - name: Installing Remi Repository on the bastion host
    yum:
      name: "{{ php_remi_repo }}"
      state: present

  - name: Installing PHP packages in the bastion host
    yum:
      name:  "{{ item }}"
      state: present
    loop: "{{ php_modules }}"

  - name: Creating a symbolic link in the bastion host
    file:
      src: "{{ php_src }}"
      dest: "{{ php_dest }}"
      owner: root
      group: root
      state: link
      force: yes

  ##################################################
  #                                                #
  #   Wordpress CLI installation                   #
  #                                                #
  ##################################################

  - name: Downlading WP CLI for Wordpress configuration
    shell:
      chdir: "{{ wp_working_dir }}"
      cmd: curl -O "{{ wp_cli_url }}"

  - name: Making wp-cli.phar file executable
    shell:
      chdir: "{{ wp_working_dir }}"
      cmd: chmod +x wp-cli.phar
  - name: Moving wp-cli.phar to "{{ wp_cli_bin_path }}"
    shell:
      chdir: "{{ wp_working_dir }}"
      cmd: sudo mv wp-cli.phar "{{ wp_cli_bin_path }}"

  ##################################################
  #                                                #
  #   Python MySQL libraries installation need by  #
  #   Ansible                                      #
  ##################################################

  - name: Installing Python MySQL support libraries for handling MySQL/MariaDB configuration throught Ansible
    yum:
      name: MySQL-python
      state: latest

  ##################################################
  #                                                #
  #   MySQL database configuration                 #
  #                                                #
  ##################################################

  - name: Creating a user account *wordpress* in MySQL/MariaDB
    mysql_user:
      name: "{{ mysql_wp_db_user }}"
      password: "{{ mysql_wp_db_password }}"
      priv: "{{ mysql_wp_user_privileges }}"
      host: "%"
      state: present
      login_host: "{{ mysql_wp_db_host }}"
      login_user: "{{ mysql_login_user }}"
      login_password: "{{ mysql_root_password }}"

  - name: Creating a new database named *wordpress* in MySQL/MariaDB
    mysql_db:
      name: "{{ mysql_wp_db_name }}"
      state: present
      login_host: "{{ mysql_wp_db_host }}"
      login_user: "{{ mysql_login_user }}"
      login_password: "{{ mysql_root_password }}"

  ##################################################
  #                                                #
  #   Wordpress CLI settings                       #
  #                                                #
  ##################################################

  - name: Applying settings to Wordpress
    shell:
      chdir: "{{ wp_working_dir }}"
      cmd: /usr/local/bin/wp core install --url="{{ wp_url }}" --title="{{ wp_title }}" --admin_user="{{ wp_admin_user }}" --admin_password="{{ wp_admin_password }}" --admin_email="{{ wp_admin_email }}"
